# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnu
MACHINETYPE	:= arm
PLATFORM	:= arm-unknown-linux-gnu
FULLOSTYPE	:= unknown-linux-gnu
