# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = arm-linux-gcc
STRIP = arm-linux-strip

# Package name and version number:

PROGRAM_PREFIX = chocolate-
PACKAGE = chocolate-doom
PACKAGE_NAME = Chocolate Doom
PACKAGE_STRING = Chocolate Doom 2.2.1
PACKAGE_TARNAME = chocolate-doom
PACKAGE_VERSION = 2.2.1

# Documentation files to distribute with packages.

DOC_FILES = README        \
            README.Music  \
            COPYING       \
            ChangeLog     \
            NEWS

